spring:
  jackson:
    serialization:
      indent_output: true
  datasource:
    url: jdbc:postgresql://topcoderdb:5432/postgres
    username: postgres
    password: topcoder872
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: cdm
tempDir: "/temp/"
compileTimeout: 2000
server:
  port: 8084