openapi: 3.0.0
info:
  version: 1.0.0
  title: TopCoder Archive
  description: TopCoder Archive
servers:
  - url: 'http://localhost:8080/api/v1'

tags:
  - name: Problems
    description: Problems
  - name: Submissions
    description: Submissions

paths:
  /problems:
    $ref: "./paths/problems.yaml"
  /problems/{id}:
    $ref: "./paths/problems-id.yaml"
  /submission:
    $ref: "./paths/submission.yaml"
